### ISSUE TITLE
Add calculator pop-up support

### ISSUE THREAD

**Issue by DECAHTHUK** [khadievedem/asus-zenbook-numpad-driver-rs#11]
A calculator app should pop-up when touching the left upper corner of the touchpad. User should somehow configure himself, which app to use(i dont think that all of the systems use the same app for the calculator)

**Comment by DECAHTHUK** [comment]
this may be not a calculator at all, just a funny feature for fast acces for some app

**Comment by eekhdv** [comment]
Wow! Sounds great :-)
